import { makeStyles } from "@material-ui/core/styles";

export default makeStyles(() => ({
  slide: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    backgroundSize: "cover",
    height: "100%",
    backgroundColor: "white",
    position: "relative",
    //  backgroundColor: "#edeff0",
    zIndex: 2,
    //  "& img": {
    //    height: "50%",
    //  },
  },
  arrowRight: {
    width: "4%",
    height: "5%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "5px 15px",
    border: "1px solid",
    fontSize: "30px",
    cursor: "pointer",
    margin: "0 20px",
    position: "absolute",
    right: 0,
    backgroundColor: "white",
  },
  arrowLeft: {
    width: "4%",
    height: "5%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "5px 15px",
    border: "1px solid",
    fontSize: "30px",
    cursor: "pointer",
    margin: "0 20px",
    backgroundColor: "white",
    position: "absolute",
  },
  indicators: {
    width: "40px",
    height: "0px",
    cursor: "pointer",
    border: "1px solid",
    margin: "0 3px",
    marginBottom: "2px",
    "&.active": {
      borderBottom: "3px solid !important",
      marginBottom: 0,
    },
    transition: "all .1s",
  },
  slideContainer: {
    position: "relative",
    cursor: "pointer",
    "& .indicators": {
      position: "absolute",
      width: "100%",
      height: "44px",
      overflow: "hidden",
      bottom: "30px",
      alignItems: "flex-end",
      zIndex: 1,
      marginTop: "-100px !important",
      padding: 0,
    },
    "&:hover": {
      "& .indicators img": {
        height: "40px",
      },
    },
    "& .react-slideshow-container": {
      position: "relative",
    },
  },
}));
