export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  TOGGLE_WISHLIST: "TOGGLE_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CHANGE_QTY_PRODUCT: "CHANGE_QTY_PRODUCT",
  SET_CART: "SET_CART",
};
