import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  btnOrderWithOutline: {
    border: "none",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: "12px",
    fontWeight: "bold",
    textTransform: "uppercase",
    color: "white",
    backgroundColor: "black",
    cursor: "pointer",
    flexGrow: 1,
    position: "relative",
    transition: "all .7s",
    "&::before": {
      borderBottom: "1px solid black",
      borderLeft: "1px solid black",
      bottom: "-3px",
      height: "3px",
      left: "2px",
      width: "100%",
      display: "block",
      position: "absolute",
      transition: ".1s cubic-bezier(0.3, 0, 0.45, 1)",
      content: "''",
    },
    "&::after": {
      borderTop: "1px solid black",
      borderRight: "1px solid black",
      height: "100%",
      right: "-3px",
      bottom: "-3px",
      width: "3px",
      display: "block",
      position: "absolute",
      transition: ".1s cubic-bezier(0.3, 0, 0.45, 1)",
      content: "''",
    },
    transition: "all .1s",
    "&:hover": {
      color: "#767677",

      "& svg": {
        color: "#767677",
        transition: "color .1s",
      },
    },
    "&:active": {
      transform: "translate(3px, 3px)",
      "&::after": {
        borderTop: "0px solid black",
        borderRight: "1px solid black",
        height: "100%",
        right: "0px",
        bottom: "0px",
        width: "3px",
        display: "block",
        position: "absolute",
        transition: ".1s cubic-bezier(0.3, 0, 0.45, 1)",
      },
      "&::before": {
        borderBottom: "0px solid black",
        borderLeft: "1px solid black",
        bottom: "0px",
        height: "3px",
        left: "0px",
        width: "100%",
        display: "block",
        position: "absolute",
        transition: ".1s cubic-bezier(0.3, 0, 0.45, 1)",
        content: "''",
      },
    },
  },
  btnOrder: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    border: "1px solid",
    paddingLeft: "12px",
    fontWeight: "bold",
    textTransform: "uppercase",
    color: "black",
    backgroundColor: "white",
    cursor: "pointer",
    flexGrow: 1,
    position: "relative",
    transition: "color .1s",
    "&:hover": {
      color: "#767677",
      "& svg": {
        color: "#767677",
        transition: "color .1s",
      },
    },
  },
  btnText: {
    textOverflow: "ellipsis",
    overflow: "hidden",
    whiteSpace: "nowrap",
    fontSize: "15px",
    letterSpacing: "1px",
  },
}));
