import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  btnOrderWithOutline: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: "12px",
    fontWeight: "bold",
    textTransform: "uppercase",
    color: "white",
    backgroundColor: "black",
    cursor: "pointer",
    flexGrow: 1,
    position: "relative",
    "&::before": {
      borderBottom: "1px solid black",
      borderLeft: "1px solid black",
      bottom: "-4px",
      height: "3px",
      left: "3px",
      width: "100%",
      display: "block",
      position: "absolute",
      transition: ".1s cubic-bezier(0.3, 0, 0.45, 1)",
      content: "''",
    },
    "&::after": {
      borderTop: "1px solid black",
      borderRight: "1px solid black",
      height: "100%",
      right: "-4px",
      bottom: "-3px",
      width: "3px",
      display: "block",
      position: "absolute",
      transition: ".1s cubic-bezier(0.3, 0, 0.45, 1)",
      content: "''",
    },
    transition: "color .1s",
    "&:hover": {
      color: "#767677",
      "& svg": {
        color: "#767677",
        transition: "color .1s",
      },
    },
  },
  btnOrder: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    border: "1px solid",
    paddingLeft: "12px",
    fontWeight: "bold",
    textTransform: "uppercase",
    color: "black",
    backgroundColor: "white",
    cursor: "pointer",
    flexGrow: 1,
    position: "relative",
    transition: "color .1s",
    "&:hover": {
      color: "#767677",
      "& svg": {
        color: "#767677",
        transition: "color .1s",
      },
    },
  },
  btnText: {
    textOverflow: "ellipsis",
    overflow: "hidden",
    whiteSpace: "nowrap",
    fontSize: "15px",
    letterSpacing: "1px",
  },
}));
